const skill_suggestions = [
  'web development',
  'graphic design',
  'programming',
  'data structures',
  'algorithms',
  'content writing',
  'dev-ops',
  'backend development',
  'frontend development',
  'data analysis',
  'ml-ops',
  'marketing strategy',
  'social media management',
  'photography',
  'video editing',
  'public speaking',
  'event planning',
  'ui/ux design',
  'app development',
  'project management',
  'research skills',
  'leadership',
  'time management',
  'blogging',
  'creative writing',
  'illustration',
  'animation',
  'typography',
  'public relations',
  'networking',
  'digital marketing',
  'financial literacy',
  'entrepreneurship',
  'critical thinking',
  'problem solving',
  'team collaboration',
  'seo optimization',
  'language proficiency',
  'teaching/tutoring',
  'business analysis',
  'database management',
  'data entry',
  'mobile app design',
  '3d modeling',
  'virtual reality (vr)',
  'augmented reality (ar)',
  'cybersecurity',
  'e-commerce',
  'user testing',
  'negotiation skills',
  'environmental sustainability',
  'robotics',
  'ui/ux research',
  'game development',
  'music production',
  'health and wellness',
  'ui/ux prototyping',
  'animation design',
  'branding',
  'blockchain development',
  'cloud computing',
  'computer vision',
  'cryptocurrency',
  'data visualization',
  'email marketing',
  'ethical hacking',
  'game design',
  'human-computer interaction',
  'internet of things (iot)',
  'machine learning',
  'natural language processing',
  'product management',
  'quantum computing',
  'software testing',
  'supply chain management',
  'virtual assistant development',
  'web security',
  'bioinformatics',
  'quantitative analysis',
  'bioengineering',
  'blockchain governance',
  'biochemistry',
  'chemical engineering',
  'climate modeling',
  'cognitive computing',
  'nanotechnology',
  'neuroscience',
  'quantitative research',
  'search engine optimization (seo)',
  'sustainable design',
  'systems engineering',
  'technical writing',
  'game testing',
  'cloud security',
  'wearable design',
  'ethical investing',
  'algorithmic trading',
  'financial planning',
  'strategic planning',
  'risk management',
  'investment analysis',
  'business development',
  'financial modeling',
  'project planning',
  'business strategy',
  'entrepreneurial finance',
  'leadership development',
  'business analysis',
  'corporate finance',
  'investment banking',
  'portfolio management',
  'audit and compliance',
  'performance management',
  'supply chain management',
  'inventory management',
  'logistics management',
  'business process reengineering',
  'strategic management',
  'cost accounting',
  'management consulting',
  'financial reporting',
  'strategic sourcing',
  'sales management',
  'marketing management',
  'human resource management',
  'event management',
  'supply chain optimization',
  'business intelligence',
  'financial analysis',
  'data management',
  'risk assessment',
  'supply chain analytics',
  'operations management',
];

export default skill_suggestions;
